cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .m2/repository/
    - target/

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository/"

stages:
  - delivery

Codedelivery:
  stage: delivery
  tags:
    - deploy
  script:
    #- mvn $MAVEN_CLI_OPTS clean install
    - mvn $MAVEN_CLI_OPTS deploy -DskipTests
    - echo "installing the package in local repository"
  only :
    - development


